//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestWorkflow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApproverFlow> ApproverFlows { get; set; }
        public virtual DbSet<ModuleMaster> ModuleMasters { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserRequest> UserRequests { get; set; }
    
        public virtual ObjectResult<USP_FETCH_REQ_LIST_Result> USP_FETCH_REQ_LIST(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_FETCH_REQ_LIST_Result>("USP_FETCH_REQ_LIST", idParameter);
        }
    
        public virtual ObjectResult<USP_FETCH_PENDING_REQ_Result> USP_FETCH_PENDING_REQ(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_FETCH_PENDING_REQ_Result>("USP_FETCH_PENDING_REQ", idParameter);
        }
    
        public virtual ObjectResult<USP_APPROVE_USER_REQUEST_Result> USP_APPROVE_USER_REQUEST(Nullable<int> reqId, Nullable<int> approverId, Nullable<bool> isSystemGenerated)
        {
            var reqIdParameter = reqId.HasValue ?
                new ObjectParameter("ReqId", reqId) :
                new ObjectParameter("ReqId", typeof(int));
    
            var approverIdParameter = approverId.HasValue ?
                new ObjectParameter("ApproverId", approverId) :
                new ObjectParameter("ApproverId", typeof(int));
    
            var isSystemGeneratedParameter = isSystemGenerated.HasValue ?
                new ObjectParameter("IsSystemGenerated", isSystemGenerated) :
                new ObjectParameter("IsSystemGenerated", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_APPROVE_USER_REQUEST_Result>("USP_APPROVE_USER_REQUEST", reqIdParameter, approverIdParameter, isSystemGeneratedParameter);
        }
    
        public virtual ObjectResult<USP_REJECT_REQUEST_Result> USP_REJECT_REQUEST(Nullable<int> reqId, Nullable<int> approverId, Nullable<bool> isSystemGenerated)
        {
            var reqIdParameter = reqId.HasValue ?
                new ObjectParameter("ReqId", reqId) :
                new ObjectParameter("ReqId", typeof(int));
    
            var approverIdParameter = approverId.HasValue ?
                new ObjectParameter("ApproverId", approverId) :
                new ObjectParameter("ApproverId", typeof(int));
    
            var isSystemGeneratedParameter = isSystemGenerated.HasValue ?
                new ObjectParameter("IsSystemGenerated", isSystemGenerated) :
                new ObjectParameter("IsSystemGenerated", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_REJECT_REQUEST_Result>("USP_REJECT_REQUEST", reqIdParameter, approverIdParameter, isSystemGeneratedParameter);
        }
    }
}
